import{a as B}from"./assets/vendor-B1ZHW564.js";(function(){const o=document.createElement("link").relList;if(o&&o.supports&&o.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))s(t);new MutationObserver(t=>{for(const r of t)if(r.type==="childList")for(const a of r.addedNodes)a.tagName==="LINK"&&a.rel==="modulepreload"&&s(a)}).observe(document,{childList:!0,subtree:!0});function n(t){const r={};return t.integrity&&(r.integrity=t.integrity),t.referrerPolicy&&(r.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?r.credentials="include":t.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function s(t){if(t.ep)return;t.ep=!0;const r=n(t);fetch(t.href,r)}})();const $="https://pixabay.com/api/",C="49710889-4feda6e3f5a5dc4aa4d4bbd5f",P=15;async function I(e,o){return(await B.get($,{params:{key:C,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:o}})).data}const p=document.getElementById("gallery"),y=document.getElementById("loader"),h=document.getElementById("load-more-btn");let d=null;function M(){return d||(d=new SimpleLightbox(".gallery a",{captionsData:"alt",captionDelay:250})),d}function i(e){return`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round">${e}</svg>`}const l={likes:i('<path d="M20.84 4.61a5.5 5.5 0 0 0-7.78 0L12 5.67l-1.06-1.06a5.5 5.5 0 0 0-7.78 7.78l1.06 1.06L12 21.23l7.78-7.78 1.06-1.06a5.5 5.5 0 0 0 0-7.78z"/>'),views:i('<path d="M1 12s4-8 11-8 11 8 11 8-4 8-11 8-11-8-11-8z"/><circle cx="12" cy="12" r="3"/>'),comments:i('<path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/>'),downloads:i('<polyline points="8 17 12 21 16 17"/><line x1="12" y1="12" x2="12" y2="21"/><path d="M20.88 18.09A5 5 0 0 0 18 9h-1.26A8 8 0 1 0 3 16.29"/>')};function x(e){const o=e.map(({webformatURL:n,largeImageURL:s,tags:t,likes:r,views:a,comments:E,downloads:v},w)=>`
      <li class="gallery-item" style="animation-delay:${w%15*40}ms">
        <a href="${s}" data-lightbox="gallery">
          <img src="${n}" alt="${t}" loading="lazy" />
        </a>
        <div class="image-meta">
          <span class="meta-item">${l.likes}${r}</span>
          <span class="meta-item">${l.views}${a}</span>
          <span class="meta-item">${l.comments}${E}</span>
          <span class="meta-item">${l.downloads}${v}</span>
        </div>
        <p class="image-tags">${t}</p>
      </li>`).join("");p.insertAdjacentHTML("beforeend",o),M().refresh()}function A(){p.innerHTML=""}function O(){y.classList.remove("hidden")}function g(){y.classList.add("hidden")}function z(){h.classList.remove("hidden")}function f(){h.classList.add("hidden")}const R=15;let b="",c=1,m=0;const k=document.getElementById("search-form"),q=document.getElementById("load-more-btn");function u(e){iziToast.error({message:e,position:"topRight",backgroundColor:"#13131a",messageColor:"#f0f0f5",iconColor:"#ff6b35",progressBarColor:"#ff6b35",titleColor:"#ff6b35",timeout:4e3,balloon:!1})}function H(e){iziToast.info({message:e,position:"topRight",backgroundColor:"#13131a",messageColor:"#f0f0f5",iconColor:"#e8ff47",progressBarColor:"#e8ff47",timeout:4e3,balloon:!1})}function S(){const e=document.querySelector(".gallery-item");if(!e)return;const o=e.getBoundingClientRect().height;window.scrollBy({top:o*2,behavior:"smooth"})}function _(){return c*R>=m}async function L(e=!1){O(),e&&f();try{const o=await I(b,c);m=o.totalHits;const n=o.hits;if(e&&(A(),n.length===0)){g(),u("Sorry, there are no images matching your search query. Please try again!");return}x(n),e||S(),_()?(f(),H("We're sorry, but you've reached the end of search results.")):z()}catch(o){f(),u("Something went wrong. Please try again later."),console.error(o)}finally{g()}}k.addEventListener("submit",async e=>{e.preventDefault();const o=e.currentTarget.elements.query.value.trim();if(!o){u("Please enter a search term.");return}b=o,c=1,m=0,await L(!0)});q.addEventListener("click",async()=>{c+=1,await L(!1)});
//# sourceMappingURL=index.js.map
