import{a as L,S as E,i as u}from"./assets/vendor-73qhTu8_.js";(function(){const t=document.createElement("link").relList;if(t&&t.supports&&t.supports("modulepreload"))return;for(const o of document.querySelectorAll('link[rel="modulepreload"]'))a(o);new MutationObserver(o=>{for(const r of o)if(r.type==="childList")for(const i of r.addedNodes)i.tagName==="LINK"&&i.rel==="modulepreload"&&a(i)}).observe(document,{childList:!0,subtree:!0});function n(o){const r={};return o.integrity&&(r.integrity=o.integrity),o.referrerPolicy&&(r.referrerPolicy=o.referrerPolicy),o.crossOrigin==="use-credentials"?r.credentials="include":o.crossOrigin==="anonymous"?r.credentials="omit":r.credentials="same-origin",r}function a(o){if(o.ep)return;o.ep=!0;const r=n(o);fetch(o.href,r)}})();const w="https://pixabay.com/api/",B="55782730-508b64862a8909659e50ec608",P=15;async function v(e,t){return(await L.get(w,{params:{key:B,q:e,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:P,page:t}})).data}const f=document.getElementById("gallery"),m=document.getElementById("loader"),g=document.getElementById("load-more-btn"),I=new E(".gallery a",{captionsData:"alt",captionDelay:250});function $(e){const t=e.map(({webformatURL:n,largeImageURL:a,tags:o,likes:r,views:i,comments:h,downloads:b})=>`
        <li class="gallery-item">
          <a href="${a}">
            <img src="${n}" alt="${o}" loading="lazy" />
          </a>
          <div class="image-info">
            <p class="image-info-item"><b>Likes</b>${r}</p>
            <p class="image-info-item"><b>Views</b>${i}</p>
            <p class="image-info-item"><b>Comments</b>${h}</p>
            <p class="image-info-item"><b>Downloads</b>${b}</p>
          </div>
        </li>`).join("");f.insertAdjacentHTML("beforeend",t),I.refresh()}function A(){f.innerHTML=""}function M(){m.classList.remove("hidden")}function O(){m.classList.add("hidden")}function R(){g.classList.remove("hidden")}function d(){g.classList.add("hidden")}const S=15;let y="",s=1,l=0;const q=document.getElementById("search-form"),_=document.getElementById("load-more-btn");function c(e){u.error({message:e,position:"topRight",timeout:4e3})}function H(e){u.info({message:e,position:"topRight",timeout:4e3})}function x(){const e=document.querySelector(".gallery-item");if(!e)return;const t=e.getBoundingClientRect().height;window.scrollBy({top:t*2,behavior:"smooth"})}function C(){return s*S>=l}async function p(e=!1){d(),M(),e&&A();try{const t=await v(y,s);l=t.totalHits;const n=t.hits;if(n.length===0){c("Sorry, there are no images matching your search query. Please try again!");return}$(n),e||x(),C()?(d(),H("We're sorry, but you've reached the end of search results.")):R()}catch(t){c("Something went wrong. Please try again later."),console.error(t)}finally{O()}}q.addEventListener("submit",async e=>{e.preventDefault();const t=e.currentTarget.elements.query.value.trim();if(!t){c("Please enter a search term.");return}y=t,s=1,l=0,await p(!0)});_.addEventListener("click",async()=>{s+=1,await p(!1)});
//# sourceMappingURL=index.js.map
